Implement Bottom Bar UI
NguyenVanViet2004/FE-Shoes-Ecommerce pull request #20
Opened 2024-07-14 07:25 UTC by KMTus

## Related issues
Resolve #6 

## Summary
Creat bottom bar all screen :  home , notification , favourite , account , oder
tsconfig.json :     "noImplicitAny": false -- use to any
package : Add  library react-dom , d3-shape , animatable , curved-bottom-bar, type vecto icon
fix err yarn lint
## How to test
call function 

## Concern points

## Screenshots

![Screenshot 2024-07-12 095158](https://github.com/user-attachments/assets/7cb2f614-9e4c-4e3a-b233-f291ba315811)

2024-07-14 16:08 UTC, NguyenVanViet2004 requested changes
Why do you use the **`merge`** statement?

2024-07-14 16:35 UTC, KMTus commented
> Why do you use the **`merge`** statemen
 If there is no defined process for using rebase, team members might misuse it, leading to inconsistencies in how commits are managed
Use Git Merge instead of rebase when working in groups: Git Merge keeps the commit history and is a safer choice when working in a group.

If it's wrong or bad activity, you can guide, pls

2024-07-14 16:36 UTC, KMTus commented
> Why do you use the **`merge`** statement?

If there is no defined process for using rebase, team members might misuse it, leading to inconsistencies in how commits are managed
Use Git Merge instead of rebase when working in groups: Git Merge keeps the commit history and is a safer choice when working in a group.

If it's wrong or bad activity, you can guide, pls

2024-07-15 01:21 UTC, NguyenVanViet2004 commented
> > Why do you use the **`merge`** statement?
> 
> If there is no defined process for using rebase, team members might misuse it, leading to inconsistencies in how commits are managed Use Git Merge instead of rebase when working in groups: Git Merge keeps the commit history and is a safer choice when working in a group.
> 
> If it's wrong or bad activity, you can guide, pls

Reset commit and rebase `feature` branch from `main`

2024-07-16 12:07 UTC, NguyenVanViet2004 commented on package.json
> +    "react-native-vector-icons": "^10.1.0",
Remove it

2024-07-16 12:08 UTC, NguyenVanViet2004 commented on constants/Colors.ts
> +
Remove spacing

2024-07-16 12:10 UTC, NguyenVanViet2004 commented on components/template/BottomTab.tsx
> +    const color = isDarkMode ? colors.white : colors.black
Use getColors function

2024-07-16 12:12 UTC, NguyenVanViet2004 commented on components/template/BottomTab.tsx
> +      <TouchableOpacity
Use the tamagui button if possible

2024-07-16 12:13 UTC, NguyenVanViet2004 commented on components/atoms/Colors.tsx
Remove this component, it is unnecessary

2024-07-16 12:13 UTC, NguyenVanViet2004 commented on components/template/AccountScreen.tsx
> +const AccountScreen = (): any => {
`any` ?

2024-07-16 12:14 UTC, NguyenVanViet2004 commented on components/template/BottomTab.tsx
> +import Icon, { Icons } from '../atoms/Icons'
Use relative path

2024-07-16 12:16 UTC, NguyenVanViet2004 commented on tsconfig.json
Turn off automatic formatting codes when saving files

2024-07-17 10:15 UTC, NguyenVanViet2004 commented
![image](https://github.com/user-attachments/assets/bf913fa1-1a09-4543-97a9-f23ef5c8a7fb)


![Simulator Screenshot - iPhone 15 Pro Max - 2024-07-17 at 17 13 53](https://github.com/user-attachments/assets/cb4e7e7c-081d-4a64-971f-6365347ac80f)


<img width="389" alt="Ảnh màn hình 2024-07-17 lúc 17 14 30" src="https://github.com/user-attachments/assets/5f1d4ada-f23a-4730-8eec-11e2b6befdb9">

2024-07-17 10:15 UTC, NguyenVanViet2004 commented
Fix it

2024-07-17 16:55 UTC, KMTus commented
> Fix it

I used Dimensions to Responsive Text Bottom Bar
Hook errors, I don't use them nor create them, give solutions
![image](https://github.com/user-attachments/assets/00784561-7b4c-47d6-a923-322867875989)
The image appears is not good  
@thanhdo29 You can correct the functions and I see the problem of the greeting screen

2024-07-19 12:37 UTC, NguyenVanViet2004 commented on components/templates/FavoriteScreen.tsx
Could you change the name of this component from 'FavoriteScreen' to 'FavoriteTemplate'?

2024-07-19 12:38 UTC, NguyenVanViet2004 commented on app/BottomBar.tsx
> +      <Button
You should add the `unstyled` property here

2024-07-19 15:14 UTC, NguyenVanViet2004 approved these changes

2024-07-19 15:14 UTC, merged