Implement Account & Setting UI screen
NguyenVanViet2004/FE-Shoes-Ecommerce pull request #33
Opened 2024-07-25 19:21 UTC by thanhdo29

## Related issues
Resolve #31 

## Summary
implement account & setting ui screen

## How to test
run app

## Concern points

## Screenshots
<img src="https://github.com/user-attachments/assets/bf628dfb-14e9-4c15-a2b3-65db1adae23e" alt="homeui" width="300"/>

2024-07-28 16:28 UTC, NguyenVanViet2004 commented
![image](https://github.com/user-attachments/assets/11ab16d8-90c8-4160-ba7f-ad4103cf6323)

2024-07-28 16:28 UTC, NguyenVanViet2004 commented
![Simulator Screenshot - iPhone 15 Pro Max - 2024-07-28 at 23 27 59](https://github.com/user-attachments/assets/040ef3a8-dfc2-4962-8e0c-770e90012c13)

2024-07-28 16:33 UTC, NguyenVanViet2004 commented
![image](https://github.com/user-attachments/assets/16aaee89-31c9-4134-bfac-7e9f1997400e)

2024-07-28 16:35 UTC, NguyenVanViet2004 commented
![image](https://github.com/user-attachments/assets/2640d838-ce6e-4079-949d-80b70c8338a3)

2024-07-28 16:37 UTC, NguyenVanViet2004 commented
![image](https://github.com/user-attachments/assets/cbb7380f-4792-4576-a746-0aa9ef45b3d2)

2024-07-28 16:39 UTC, NguyenVanViet2004 commented on components/templates/AccountTemplate.tsx
>  const AccountScreen: React.FC = () => {
`AccountTemplate`

2024-07-28 16:39 UTC, NguyenVanViet2004 commented on components/templates/AccountTemplate.tsx
> +            marginVertical={24}>{t('account.account')}</Text>
Why don't you use the title of `Header component`?

2024-07-28 16:42 UTC, NguyenVanViet2004 commented on components/molecules/common/Header.tsx
> +        backgroundColor={colors.white}
is `backgroundColor` necessary?

2024-07-28 16:43 UTC, NguyenVanViet2004 commented on components/templates/AccountTemplate.tsx
> +          <ChooseMethod
I think you should use `map` here, what do you think?

2024-07-28 16:44 UTC, NguyenVanViet2004 commented on locales/en.json
> +        "eneble-FaceID-For-LogIn":"Eneble Face ID For Log In",
use `Camel Case`

2024-07-31 15:23 UTC, NguyenVanViet2004 commented on components/molecules/ChooseMethod.tsx
> +    props.onCheckedChange?.(checked)
I do not understand this line, can you explain it?

2024-07-31 15:24 UTC, NguyenVanViet2004 commented on components/molecules/common/Header.tsx
> +        backgroundColor={colors.white}
what about this comment?

2024-07-31 15:25 UTC, NguyenVanViet2004 commented on components/templates/AccountTemplate.tsx
> +    name: any, size: number, color: any): React.ReactElement => {
why `name` is any?

2024-07-31 15:28 UTC, NguyenVanViet2004 requested changes
Please fix all bugs

2024-07-31 17:18 UTC, thanhdo29 commented on components/molecules/ChooseMethod.tsx
> +    props.onCheckedChange?.(checked)
- setIsChecked() is used to update the switch's state if it changes
- if Switch changes then props.onCheckedChange?.(checked) will be called to propagate the current state to the AccountTemeplate

2024-08-01 11:52 UTC, NguyenVanViet2004 commented on components/templates/AccountTemplate.tsx
> +  type IconType = 'MaterialCommunityIcons' | 'AntDesign' | 'Ionicons'
If I want to pass a different data type, how can I do that?

2024-08-02 04:52 UTC, NguyenVanViet2004 requested changes

2024-08-02 04:52 UTC, NguyenVanViet2004 commented on components/molecules/common/Header.tsx
> +  label?: string
Why don't you use `title`?

2024-08-02 04:52 UTC, NguyenVanViet2004 commented on components/templates/AccountTemplate.tsx
> +    IconComponent: any,
it should be in the `atoms` folder

2024-08-02 09:36 UTC, NguyenVanViet2004 commented
|--|--|
|---|---|
|![image](https://github.com/user-attachments/assets/08826e63-b19b-4641-aa1c-449da158cb4f)|![image](https://github.com/user-attachments/assets/e93aebf1-546a-45cc-b4f4-e6b44aef308d)|

2024-08-02 09:37 UTC, NguyenVanViet2004 commented
https://github.com/NguyenVanViet2004/FE-Shoes-Ecommerce/pull/33/files#r1694280303

2024-08-02 14:16 UTC, NguyenVanViet2004 approved these changes

2024-08-02 14:16 UTC, merged